### ISSUE TITLE
转成PDF后提示 This Chapter is not free

### ISSUE THREAD

**Issue by Fantasia1999** [TeddyNight/zhongxin_downloader#1]

**Comment by TeddyNight** [comment]
有文件么？没仔细看过，都是epub直接保存

**Comment by Fantasia1999** [comment]
有一个动物王朝的书，里边后边的章节都是空白的。
这个下载器应该不用登录吧:)


 
---原始邮件---
发件人: "TeddyNight"<notifications@github.com&gt;
发送时间: 2020年2月9日 13:07:10
收件人: "TeddyNight/zhongxin_downloader"<zhongxin_downloader@noreply.github.com&gt;;
抄送: "5chenglin"<1085505179@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [TeddyNight/zhongxin_downloader] 转成PDF后提示 This Chapter is not free (#1)



有文件么？没仔细看过，都是epub直接保存

**Comment by TeddyNight** [comment]
是，我看了中信的网站，提示要登陆，还有其他的书提示这个么

**Comment by TeddyNight** [comment]
我现在看看咋改一下
