### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by plybb** [TeddyNight/zhongxin_downloader#2]
怎么运行不了呢，需要安装依赖?谢谢Up

**Comment by TeddyNight** [comment]
不知道你说的啥问题，如果是提示requests找不到的话就安装requests: ubuntu下可以直接apt-get install python3-requests，其他发行版自己Google...

**Comment by TeddyNight** [comment]
用python3运行

**Comment by plybb** [comment]
在Python3.6输入命令os.system("start explorer zx.py文件目录")？get clone之后，用CMD也没运行成功，麻烦告知一下启动脚本的命令

**Comment by Fantasia1999** [comment]
他这个有些命令是Linux环境下的，如果在CMD运行，需要把对应的部分做一下修改，或者直接在Linux平台运行脚本。

**Comment by plybb** [comment]
@5chenglin 在windows 7下，安装了Python3.6，怎么运行呢？

**Comment by TeddyNight** [comment]
对的，脚本里面的命令是在linux下的，建议还是用linux或者wsl
